'use strict';

function generateConfig(dialPlanConfiguration) {
  if (!dialPlanConfiguration || typeof dialPlanConfiguration !== 'object' || !Array.isArray(dialPlanConfiguration.contexts)) {
    // Basic validation of the top-level structure
    console.error("Invalid dialPlanConfiguration structure: 'contexts' array is missing or invalid.", dialPlanConfiguration);
    return `; Error: Invalid dial plan configuration structure provided.
; Expected an object with a 'contexts' array.
`;
  }

  let output = "; Generated by Outbound Dialer App\n\n";

  for (const context of dialPlanConfiguration.contexts) {
    if (!context || typeof context.name !== 'string' || !context.name.trim()) {
      output += "; Skipping invalid context (name missing or empty).\n";
      continue;
    }
    output += `[${context.name.trim()}]\n`;

    if (!Array.isArray(context.extensions)) {
      output += "; Warning: Context has no 'extensions' array or it's invalid.\n\n";
      continue;
    }

    for (const extension of context.extensions) {
      if (!extension || typeof extension.exten !== 'string' || !extension.exten.trim()) {
        output += ";   Skipping invalid extension (exten missing or empty).\n";
        continue;
      }
      if (!Array.isArray(extension.priorities) || extension.priorities.length === 0) {
        output += `;   Skipping extension '${extension.exten.trim()}' (no priorities defined).\n`;
        continue;
      }

      let currentPriorityValue = 0; // Reset for each new extension logic

      for (const prio of extension.priorities) {
        if (!prio || typeof prio.app !== 'string' || !prio.app.trim()) {
          output += `;     Skipping invalid priority for exten '${extension.exten.trim()}' (app missing or empty).\n`;
          continue;
        }

        let priorityForOutput;
        if (typeof prio.priority === 'number') {
          priorityForOutput = prio.priority;
          currentPriorityValue = prio.priority;
        } else if (String(prio.priority).toLowerCase() === 'n') {
          if (currentPriorityValue === 0) {
            // This is the first priority for this extension, and it's 'n'.
            // Asterisk would typically require a '1' or a label before 'n'.
            // Let's default to 1 for this case, as 'n' alone here is ambiguous without a start.
            console.warn(`Priority 'n' used as first priority for exten '${extension.exten.trim()}'. Defaulting to 1.`);
            priorityForOutput = 1;
            currentPriorityValue = 1;
          } else {
            priorityForOutput = 'n';
            // currentPriorityValue remains the last numeric value for subsequent 'n' calculations by Asterisk
          }
        } else if (!prio.hasOwnProperty('priority') && currentPriorityValue === 0 && extension.priorities.indexOf(prio) === 0) {
            // First priority, and 'priority' key is missing, assume '1'
            priorityForOutput = 1;
            currentPriorityValue = 1;
        } else {
          // Invalid or unexpected priority value when a number or 'n' was expected
          console.warn(`Invalid priority value '${prio.priority}' for exten '${extension.exten.trim()}'. Defaulting to 'n' (assuming it follows a numeric one).`);
          priorityForOutput = 'n';
        }

        const appData = prio.appdata !== undefined && prio.appdata !== null ? String(prio.appdata) : '';
        output += `exten => ${extension.exten.trim()},${priorityForOutput},${prio.app.trim()}(${appData})\n`;

        if (typeof priorityForOutput === 'number') {
            currentPriorityValue = priorityForOutput;
        }
      }
      output += "\n"; // Add a blank line after each extension's priorities for readability
    }
    output += "\n"; // Add a blank line after each context
  }
  return output;
}

module.exports = { generateConfig };
